### ISSUE TITLE
@nativescript/ios alpha.0 Error: Unable to generate metadata for x86_64

### ISSUE THREAD

**Issue by felixkrautschuk** [NativeScript/ios#237]
I just tried adding the latest alpha version of the ios runtime and I am not able to build the project anymore (even with new created empty project).

I know it is just the alpha, just want to make sure that issues are recognized as early as possible.

I am working with Xcode 15.2 and tested a newly created project in Simulator:

> Project successfully prepared (ios)
> Building project...
> Xcode build...
> No errors found.
> ./.build_env_vars.sh: line 515: declare: UID: readonly variable
> NSLD: Swift bridging header '*-Swift.h' not found under '/Users/felixkrautschuk/Library/Developer/Xcode/DerivedData/nsruntimealpha-dzwudxpaetfaodfshlafatmejrlo/Build/Intermediates.noindex/nsruntimealpha.build/Debug-iphonesimulator/nsruntimealpha.build/Objects-normal/x86_64'
> Generating metadata...~/Downloads/ns-runtime-alpha/platforms/ios/internal/metadata-generator-x86_64/bin ~/Downloads/ns-runtime-alpha/platforms/ios
> Python version: 3.9.6 (default, Dec  7 2023, 05:42:47) 
> [Clang 15.0.0 (clang-1500.1.0.2.5)]
> Generating metadata for x86_64
> Saving metadata generation's stderr stream to: /Users/felixkrautschuk/Downloads/ns-runtime-alpha/platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-x86_64.txt
> Error: Unable to generate metadata for x86_64.
> dyld[38933]: Library not loaded: @rpath/libc++.1.dylib
>   Referenced from: <11164D07-F868-3EF7-91FC-4EF036DEFB36> /Users/felixkrautschuk/Downloads/ns-runtime-alpha/platforms/ios/internal/metadata-generator-x86_64/bin/objc-metadata-generator
>   Reason: no LC_RPATH's found
> 
> Command Ld failed with a nonzero exit code
> note: Using codesigning identity override: 
> note: Run script build phase 'NativeScript PreBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'nsruntimealpha' from project 'nsruntimealpha')
> note: Run script build phase 'NativeScript PostBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'nsruntimealpha' from project 'nsruntimealpha')
> note: Run script build phase 'NativeScript PreLink' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'nsruntimealpha' from project 'nsruntimealpha')
> ** BUILD FAILED **

Sample app:
[ns-runtime-alpha.zip](https://github.com/NativeScript/ios/files/14124965/ns-runtime-alpha.zip)

**Comment by rigor789** [comment]
Could you also attach ` /Users/felixkrautschuk/Downloads/ns-runtime-alpha/platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-x86_64.txt` - I just downloaded your sample, and it built/ran on my machine - curious to dig into this further.

**Comment by felixkrautschuk** [comment]
@rigor789 thanks for your fast response!

[metadata-generation-stderr-x86_64.txt](https://github.com/NativeScript/ios/files/14127549/metadata-generation-stderr-x86_64.txt)

And just in case you are also interested in my development environment:

```yaml
OS: macOS 14.3
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Shell: /bin/zsh
node: 20.10.0
npm: 10.2.3
nativescript: 8.6.5

# android
java: 11.0.11
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 15.2/15C500b
cocoapods: 1.14.3
python: 2.7.18
python3: 3.9.6
ruby: 2.6.10
platforms: 
  - DriverKit 23.2
  - iOS 17.2
  - macOS 14.2
  - tvOS 17.2
  - visionOS 1.0
  - watchOS 10.2
```
